### ISSUE TITLE
Not able to run sample demo colab notebook

### ISSUE THREAD

**Issue by pranavgundewar** [humanpose1/MS-SVConv#11]
After successful installation of dependencies in the notebook, I have encountered the following error-

![image](https://user-images.githubusercontent.com/37206432/135530721-b4c4998b-54ac-4f48-9ee7-a375ffe0b554.png)

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-6-ccdc9034c219> in <module>()
      6 import requests
      7 import torch
----> 8 from torch_points3d.applications.pretrained_api import PretainedRegistry
      9 from torch_points3d.core.data_transform import GridSampling3D, AddFeatByKey, AddOnes, Random3AxisRotation
     10 from torch_points3d.datasets.registration.pair import Pair

8 frames
/usr/lib/python3.7/ctypes/__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    362 
    363         if handle is None:
--> 364             self._handle = _dlopen(self._name, mode)
    365         else:
    366             self._handle = handle

OSError: /usr/local/lib/python3.7/dist-packages/torch_sparse/_version_cuda.so: undefined symbol: _ZN3c106detail23torchInternalAssertFailEPKcS2_jS2_S2_

**Comment by humanpose1** [comment]
Hi @pranavgundewar ,
Thanks for reporting the problem.
It is solved now. It was a problem of version(torch 1.9 is not compatible with the current version of torch points 3d)
I'll close the issue. If you find something else, you can reopen it.
Best,
