### ISSUE TITLE
Can i build MS-SVConv model?

### ISSUE THREAD

**Issue by jjPenguin** [humanpose1/MS-SVConv#8]
Dear humanpose1.
Thank you so much for revealing the tremendous code.
I am working on feature extraction, and i am curious about feature extraction that MS-SVConv is using
Can I make MS-SVConv model using various epochs?

Once again, thank you for your big decision.

**Comment by humanpose1** [comment]
Hi @jjPenguin ,
Thank you for your warm message. 
I am not sure to fully understand your request but if I understand well, you are asking whether you can train multiple MS-SVConv models with various epochs. With torch points3d you can even if it i not automatic.
For example, if you want to train on modelnet.
```
python train.py task=registration models=registration/ms_svconv_base model_name=MS_SVCONV_B2cm_X2_3head data=registration/modelnet_sparse_ss training=sparse_fragment_reg tracker_options.make_submission=True training.epochs=2
```
It will save a pt file on a specific folder.
then you can resume training with a different number of epoch (you have tospecify also the checkpoint_dir)

```
python train.py task=registration models=registration/ms_svconv_base model_name=MS_SVCONV_B2cm_X2_3head data=registration/modelnet_sparse_ss training=sparse_fragment_reg tracker_options.make_submission=True training.epochs=4 training.checkpoint_dir=/path/to/directory/that/contain/pt/file
```

Does it help you ?
